### PR TITLE
Add Crew Twitter profil

### PR DESCRIPTION
**Pull request by Andersos**
@elisabethirgens what about adding people Twitter profiles? Thoughts?

### CODE REVIEW

**Comment by trygve-lie** [comment]
Github accounts... we are developers after all

**Comment by Andersos** [comment]
Sure I can change this to Github accounts. Anyone else have thought on this?

**Comment by leftieFriele** [comment]
I agree, I think I put it in the about text the names of the organizers.

Have a look on the github

**Comment by Andersos** [comment]
I'll just merge this if the build is green then. Swapped out Twitter for Github.

**Pull request merged**
